/*
  Taboo card bank.

  Each card: the target `word`, plus `forbidden` — the words the clue-giver may
  NOT say. Cards are written so the forbidden list blocks the obvious routes and
  forces a creative description (that is the whole game). Kept workplace-safe so
  the game works for team socials as well as parties.
*/
export const CARDS = [
  { word: 'Pizza', forbidden: ['Cheese', 'Italian', 'Slice', 'Pepperoni', 'Dough'] },
  { word: 'Beach', forbidden: ['Sand', 'Sea', 'Sun', 'Waves', 'Holiday'] },
  { word: 'Coffee', forbidden: ['Drink', 'Caffeine', 'Morning', 'Bean', 'Starbucks'] },
  { word: 'Birthday', forbidden: ['Cake', 'Candles', 'Party', 'Presents', 'Age'] },
  { word: 'Rainbow', forbidden: ['Colours', 'Rain', 'Sky', 'Arc', 'Pot of gold'] },
  { word: 'Guitar', forbidden: ['Strings', 'Music', 'Play', 'Instrument', 'Band'] },
  { word: 'Doctor', forbidden: ['Hospital', 'Patient', 'Medicine', 'Sick', 'Nurse'] },
  { word: 'Winter', forbidden: ['Cold', 'Snow', 'Season', 'Ice', 'Christmas'] },
  { word: 'Football', forbidden: ['Ball', 'Goal', 'Sport', 'Kick', 'Team'] },
  { word: 'Library', forbidden: ['Books', 'Quiet', 'Read', 'Borrow', 'Shelves'] },
  { word: 'Elephant', forbidden: ['Trunk', 'Big', 'Grey', 'Africa', 'Tusks'] },
  { word: 'Wedding', forbidden: ['Marriage', 'Bride', 'Groom', 'Ring', 'Church'] },
  { word: 'Chocolate', forbidden: ['Sweet', 'Cocoa', 'Bar', 'Candy', 'Brown'] },
  { word: 'Airport', forbidden: ['Plane', 'Fly', 'Travel', 'Terminal', 'Luggage'] },
  { word: 'Teacher', forbidden: ['School', 'Class', 'Students', 'Learn', 'Lesson'] },
  { word: 'Umbrella', forbidden: ['Rain', 'Wet', 'Open', 'Handle', 'Cover'] },
  { word: 'Netflix', forbidden: ['Streaming', 'Watch', 'Series', 'TV', 'Subscription'] },
  { word: 'Dentist', forbidden: ['Teeth', 'Drill', 'Mouth', 'Cavity', 'Clean'] },
  { word: 'Snowman', forbidden: ['Snow', 'Carrot', 'Winter', 'Build', 'Frosty'] },
  { word: 'Passport', forbidden: ['Travel', 'Document', 'Country', 'Photo', 'Border'] },
  { word: 'Popcorn', forbidden: ['Cinema', 'Corn', 'Butter', 'Snack', 'Pop'] },
  { word: 'Volcano', forbidden: ['Lava', 'Erupt', 'Mountain', 'Ash', 'Magma'] },
  { word: 'Keyboard', forbidden: ['Type', 'Keys', 'Computer', 'Letters', 'Piano'] },
  { word: 'Honey', forbidden: ['Bees', 'Sweet', 'Sticky', 'Golden', 'Jar'] },
  { word: 'Museum', forbidden: ['Art', 'History', 'Exhibit', 'Gallery', 'Visit'] },
  { word: 'Penguin', forbidden: ['Antarctica', 'Bird', 'Ice', 'Swim', 'Black and white'] },
  { word: 'Sunglasses', forbidden: ['Eyes', 'Sun', 'Shades', 'Wear', 'Dark'] },
  { word: 'Barbecue', forbidden: ['Grill', 'Meat', 'Cook', 'Summer', 'Smoke'] },
  { word: 'Helicopter', forbidden: ['Fly', 'Blades', 'Rotor', 'Aircraft', 'Land'] },
  { word: 'Pancake', forbidden: ['Flat', 'Syrup', 'Breakfast', 'Flip', 'Batter'] },
  { word: 'Vampire', forbidden: ['Blood', 'Dracula', 'Fangs', 'Night', 'Bat'] },
  { word: 'Lighthouse', forbidden: ['Light', 'Sea', 'Ships', 'Tower', 'Coast'] },
  { word: 'Spaghetti', forbidden: ['Pasta', 'Italian', 'Noodles', 'Sauce', 'Fork'] },
  { word: 'Firefighter', forbidden: ['Fire', 'Hose', 'Truck', 'Rescue', 'Helmet'] },
  { word: 'Butterfly', forbidden: ['Wings', 'Caterpillar', 'Insect', 'Fly', 'Colourful'] },
  { word: 'Suitcase', forbidden: ['Pack', 'Travel', 'Luggage', 'Wheels', 'Clothes'] },
  { word: 'Mirror', forbidden: ['Reflection', 'Glass', 'See', 'Look', 'Bathroom'] },
  { word: 'Podcast', forbidden: ['Listen', 'Audio', 'Episode', 'Host', 'Show'] },
  { word: 'Kangaroo', forbidden: ['Australia', 'Jump', 'Pouch', 'Hop', 'Marsupial'] },
  { word: 'Toothbrush', forbidden: ['Teeth', 'Clean', 'Paste', 'Bathroom', 'Brush'] },
  { word: 'Waterfall', forbidden: ['Water', 'Fall', 'River', 'Cliff', 'Niagara'] },
  { word: 'Sandwich', forbidden: ['Bread', 'Lunch', 'Filling', 'Slices', 'Eat'] },
  { word: 'Astronaut', forbidden: ['Space', 'NASA', 'Moon', 'Rocket', 'Suit'] },
  { word: 'Pineapple', forbidden: ['Fruit', 'Spiky', 'Tropical', 'Yellow', 'Pizza'] },
  { word: 'Traffic', forbidden: ['Cars', 'Jam', 'Road', 'Slow', 'Lights'] },
  { word: 'Scissors', forbidden: ['Cut', 'Paper', 'Sharp', 'Blades', 'Hair'] },
  { word: 'Karaoke', forbidden: ['Sing', 'Microphone', 'Song', 'Lyrics', 'Bar'] },
  { word: 'Squirrel', forbidden: ['Nuts', 'Tree', 'Tail', 'Acorn', 'Park'] },
  { word: 'Camera', forbidden: ['Photo', 'Picture', 'Lens', 'Shoot', 'Flash'] },
  { word: 'Marathon', forbidden: ['Run', 'Race', 'Miles', 'Finish', 'Training'] },
  { word: 'Igloo', forbidden: ['Ice', 'Snow', 'House', 'Eskimo', 'Cold'] },
  { word: 'Password', forbidden: ['Login', 'Secret', 'Account', 'Forgot', 'Type'] },
  { word: 'Rollercoaster', forbidden: ['Ride', 'Theme park', 'Loop', 'Scream', 'Track'] },
  { word: 'Grandmother', forbidden: ['Grandma', 'Family', 'Old', 'Mother', 'Nan'] },
  { word: 'Microwave', forbidden: ['Heat', 'Food', 'Kitchen', 'Oven', 'Beep'] },
  { word: 'Tornado', forbidden: ['Wind', 'Storm', 'Spin', 'Twister', 'Destroy'] },
  { word: 'Fireworks', forbidden: ['Explode', 'Sky', 'New Year', 'Bang', 'Colours'] },
  { word: 'Escalator', forbidden: ['Stairs', 'Moving', 'Mall', 'Up', 'Step'] },
  { word: 'Detective', forbidden: ['Crime', 'Clues', 'Solve', 'Police', 'Sherlock'] },
  { word: 'Cactus', forbidden: ['Desert', 'Spikes', 'Plant', 'Water', 'Green'] },
  { word: 'Wallet', forbidden: ['Money', 'Cards', 'Pocket', 'Cash', 'Leather'] },
  { word: 'Thunderstorm', forbidden: ['Lightning', 'Rain', 'Loud', 'Clouds', 'Weather'] },
  { word: 'Bicycle', forbidden: ['Wheels', 'Pedal', 'Ride', 'Bike', 'Chain'] },
  { word: 'Nurse', forbidden: ['Hospital', 'Doctor', 'Patient', 'Care', 'Scrubs'] },
  { word: 'Treasure', forbidden: ['Gold', 'Pirate', 'Chest', 'Map', 'Buried'] },
  { word: 'Blanket', forbidden: ['Warm', 'Bed', 'Cover', 'Sleep', 'Soft'] },
  { word: 'Aquarium', forbidden: ['Fish', 'Tank', 'Water', 'Glass', 'Swim'] },
  { word: 'Compass', forbidden: ['North', 'Direction', 'Needle', 'Navigate', 'Map'] },
  { word: 'Sunflower', forbidden: ['Yellow', 'Sun', 'Tall', 'Seeds', 'Flower'] },
  { word: 'Ambulance', forbidden: ['Hospital', 'Emergency', 'Siren', 'Paramedic', 'Van'] },
  { word: 'Origami', forbidden: ['Paper', 'Fold', 'Japanese', 'Crane', 'Art'] },
  { word: 'Trampoline', forbidden: ['Jump', 'Bounce', 'Garden', 'Springs', 'Kids'] },
  { word: 'Hedgehog', forbidden: ['Spikes', 'Prickly', 'Curl', 'Garden', 'Sonic'] },
  { word: 'Calendar', forbidden: ['Dates', 'Months', 'Year', 'Days', 'Wall'] },
  { word: 'Submarine', forbidden: ['Underwater', 'Boat', 'Dive', 'Navy', 'Periscope'] },
  { word: 'Cinnamon', forbidden: ['Spice', 'Roll', 'Bun', 'Sweet', 'Stick'] },
  { word: 'Handshake', forbidden: ['Hands', 'Greet', 'Meet', 'Deal', 'Shake'] },
  { word: 'Playground', forbidden: ['Swing', 'Slide', 'Kids', 'Park', 'Play'] },
  { word: 'Chandelier', forbidden: ['Light', 'Ceiling', 'Crystal', 'Hang', 'Fancy'] },
  { word: 'Snorkel', forbidden: ['Swim', 'Breathe', 'Sea', 'Mask', 'Tube'] },
];

export function shuffledDeck() {
  const a = [...CARDS];
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
}
