/*
  Taboo card bank.

  Each card: the target `word`, plus `forbidden` — the words the clue-giver may
  NOT say. Cards are written so the forbidden list blocks the obvious routes and
  forces a creative description (that is the whole game). Kept workplace-safe so
  the game works for team socials as well as parties.

  Size matters here: a single 3-round game burns roughly 60-80 cards, so a small
  bank means back-to-back games replay the same words and the guessing gets
  trivial. Keep this list large — grouped by theme below purely for readability,
  it is shuffled flat.
*/
export const CARDS = [
  // ── Food & drink ───────────────────────────────────────────────────────────
  { word: 'Pizza', forbidden: ['Cheese', 'Italian', 'Slice', 'Pepperoni', 'Dough'] },
  { word: 'Coffee', forbidden: ['Drink', 'Caffeine', 'Morning', 'Bean', 'Starbucks'] },
  { word: 'Chocolate', forbidden: ['Sweet', 'Cocoa', 'Bar', 'Candy', 'Brown'] },
  { word: 'Popcorn', forbidden: ['Cinema', 'Corn', 'Butter', 'Snack', 'Pop'] },
  { word: 'Honey', forbidden: ['Bees', 'Sweet', 'Sticky', 'Golden', 'Jar'] },
  { word: 'Spaghetti', forbidden: ['Pasta', 'Italian', 'Noodles', 'Sauce', 'Fork'] },
  { word: 'Pancake', forbidden: ['Flat', 'Syrup', 'Breakfast', 'Flip', 'Batter'] },
  { word: 'Sandwich', forbidden: ['Bread', 'Lunch', 'Filling', 'Slices', 'Eat'] },
  { word: 'Pineapple', forbidden: ['Fruit', 'Spiky', 'Tropical', 'Yellow', 'Pizza'] },
  { word: 'Cinnamon', forbidden: ['Spice', 'Roll', 'Bun', 'Sweet', 'Stick'] },
  { word: 'Barbecue', forbidden: ['Grill', 'Meat', 'Cook', 'Summer', 'Smoke'] },
  { word: 'Burger', forbidden: ['Beef', 'Bun', 'Patty', 'Fast food', 'Chips'] },
  { word: 'Sushi', forbidden: ['Japan', 'Rice', 'Fish', 'Raw', 'Roll'] },
  { word: 'Taco', forbidden: ['Mexican', 'Shell', 'Filling', 'Tortilla', 'Wrap'] },
  { word: 'Waffle', forbidden: ['Squares', 'Breakfast', 'Syrup', 'Batter', 'Belgian'] },
  { word: 'Doughnut', forbidden: ['Ring', 'Hole', 'Sugar', 'Glaze', 'Police'] },
  { word: 'Cupcake', forbidden: ['Cake', 'Small', 'Frosting', 'Bake', 'Paper'] },
  { word: 'Ice cream', forbidden: ['Cold', 'Scoop', 'Cone', 'Dessert', 'Melt'] },
  { word: 'Lollipop', forbidden: ['Stick', 'Sweet', 'Lick', 'Candy', 'Sugar'] },
  { word: 'Cheese', forbidden: ['Milk', 'Yellow', 'Cheddar', 'Mouse', 'Dairy'] },
  { word: 'Butter', forbidden: ['Spread', 'Toast', 'Yellow', 'Dairy', 'Margarine'] },
  { word: 'Bread', forbidden: ['Loaf', 'Bake', 'Slice', 'Toast', 'Flour'] },
  { word: 'Toast', forbidden: ['Bread', 'Burn', 'Breakfast', 'Butter', 'Pop'] },
  { word: 'Cereal', forbidden: ['Milk', 'Bowl', 'Breakfast', 'Flakes', 'Spoon'] },
  { word: 'Soup', forbidden: ['Bowl', 'Spoon', 'Hot', 'Liquid', 'Broth'] },
  { word: 'Salad', forbidden: ['Lettuce', 'Vegetables', 'Bowl', 'Healthy', 'Dressing'] },
  { word: 'Curry', forbidden: ['Spicy', 'India', 'Rice', 'Sauce', 'Hot'] },
  { word: 'Ramen', forbidden: ['Noodles', 'Japan', 'Broth', 'Bowl', 'Soup'] },
  { word: 'Pretzel', forbidden: ['Twist', 'Salt', 'Snack', 'Germany', 'Bread'] },
  { word: 'Marshmallow', forbidden: ['Soft', 'White', 'Campfire', 'Sweet', 'Roast'] },
  { word: 'Watermelon', forbidden: ['Fruit', 'Green', 'Red', 'Seeds', 'Summer'] },
  { word: 'Banana', forbidden: ['Fruit', 'Yellow', 'Peel', 'Monkey', 'Bunch'] },
  { word: 'Strawberry', forbidden: ['Fruit', 'Red', 'Seeds', 'Berry', 'Jam'] },
  { word: 'Avocado', forbidden: ['Green', 'Toast', 'Stone', 'Guacamole', 'Fruit'] },
  { word: 'Mushroom', forbidden: ['Fungus', 'Pizza', 'Forest', 'Cap', 'Grow'] },
  { word: 'Pumpkin', forbidden: ['Orange', 'Halloween', 'Carve', 'Pie', 'Squash'] },
  { word: 'Garlic', forbidden: ['Vampire', 'Cloves', 'Smell', 'Bulb', 'Cook'] },
  { word: 'Pepper', forbidden: ['Salt', 'Spice', 'Black', 'Grind', 'Hot'] },
  { word: 'Ketchup', forbidden: ['Tomato', 'Sauce', 'Red', 'Bottle', 'Chips'] },
  { word: 'Smoothie', forbidden: ['Blend', 'Fruit', 'Drink', 'Straw', 'Yoghurt'] },
  { word: 'Lemonade', forbidden: ['Lemon', 'Drink', 'Sugar', 'Stand', 'Sour'] },
  { word: 'Milkshake', forbidden: ['Milk', 'Thick', 'Straw', 'Blend', 'Ice cream'] },
  { word: 'Champagne', forbidden: ['Bubbles', 'Celebrate', 'Cork', 'Wine', 'Pop'] },
  { word: 'Chopsticks', forbidden: ['Sticks', 'Asian', 'Eat', 'Rice', 'Pair'] },
  { word: 'Leftovers', forbidden: ['Food', 'Fridge', 'Yesterday', 'Reheat', 'Meal'] },
  { word: 'Buffet', forbidden: ['Food', 'All you can eat', 'Plate', 'Queue', 'Restaurant'] },
  { word: 'Picnic', forbidden: ['Basket', 'Blanket', 'Outside', 'Food', 'Park'] },
  { word: 'Recipe', forbidden: ['Cook', 'Instructions', 'Ingredients', 'Book', 'Bake'] },

  // ── Animals ────────────────────────────────────────────────────────────────
  { word: 'Elephant', forbidden: ['Trunk', 'Big', 'Grey', 'Africa', 'Tusks'] },
  { word: 'Penguin', forbidden: ['Antarctica', 'Bird', 'Ice', 'Swim', 'Black and white'] },
  { word: 'Kangaroo', forbidden: ['Australia', 'Jump', 'Pouch', 'Hop', 'Marsupial'] },
  { word: 'Butterfly', forbidden: ['Wings', 'Caterpillar', 'Insect', 'Fly', 'Colourful'] },
  { word: 'Squirrel', forbidden: ['Nuts', 'Tree', 'Tail', 'Acorn', 'Park'] },
  { word: 'Hedgehog', forbidden: ['Spikes', 'Prickly', 'Curl', 'Garden', 'Sonic'] },
  { word: 'Giraffe', forbidden: ['Neck', 'Tall', 'Africa', 'Spots', 'Zoo'] },
  { word: 'Monkey', forbidden: ['Banana', 'Tree', 'Ape', 'Swing', 'Zoo'] },
  { word: 'Dolphin', forbidden: ['Sea', 'Swim', 'Smart', 'Fish', 'Jump'] },
  { word: 'Shark', forbidden: ['Teeth', 'Sea', 'Jaws', 'Fin', 'Bite'] },
  { word: 'Octopus', forbidden: ['Tentacles', 'Eight', 'Sea', 'Ink', 'Arms'] },
  { word: 'Turtle', forbidden: ['Shell', 'Slow', 'Sea', 'Reptile', 'Tortoise'] },
  { word: 'Snake', forbidden: ['Slither', 'Hiss', 'Reptile', 'Venom', 'Long'] },
  { word: 'Owl', forbidden: ['Bird', 'Night', 'Hoot', 'Wise', 'Eyes'] },
  { word: 'Eagle', forbidden: ['Bird', 'Fly', 'Beak', 'America', 'Prey'] },
  { word: 'Parrot', forbidden: ['Bird', 'Talk', 'Colourful', 'Pirate', 'Feathers'] },
  { word: 'Peacock', forbidden: ['Feathers', 'Tail', 'Bird', 'Blue', 'Show off'] },
  { word: 'Flamingo', forbidden: ['Pink', 'Leg', 'Bird', 'Stand', 'Water'] },
  { word: 'Bat', forbidden: ['Night', 'Fly', 'Cave', 'Blind', 'Vampire'] },
  { word: 'Frog', forbidden: ['Jump', 'Green', 'Pond', 'Croak', 'Toad'] },
  { word: 'Crocodile', forbidden: ['Teeth', 'River', 'Reptile', 'Snap', 'Alligator'] },
  { word: 'Lion', forbidden: ['King', 'Mane', 'Roar', 'Africa', 'Jungle'] },
  { word: 'Tiger', forbidden: ['Stripes', 'Orange', 'Big cat', 'Jungle', 'Roar'] },
  { word: 'Panda', forbidden: ['Bamboo', 'China', 'Black and white', 'Bear', 'Zoo'] },
  { word: 'Polar bear', forbidden: ['Arctic', 'White', 'Bear', 'Ice', 'Cold'] },
  { word: 'Camel', forbidden: ['Hump', 'Desert', 'Sand', 'Ride', 'Water'] },
  { word: 'Horse', forbidden: ['Ride', 'Gallop', 'Saddle', 'Stable', 'Hooves'] },
  { word: 'Sheep', forbidden: ['Wool', 'Baa', 'Farm', 'Lamb', 'Flock'] },
  { word: 'Cow', forbidden: ['Milk', 'Moo', 'Farm', 'Beef', 'Udder'] },
  { word: 'Pig', forbidden: ['Oink', 'Farm', 'Bacon', 'Mud', 'Pink'] },
  { word: 'Chicken', forbidden: ['Egg', 'Cluck', 'Farm', 'Bird', 'Nugget'] },
  { word: 'Duck', forbidden: ['Quack', 'Pond', 'Bird', 'Swim', 'Bread'] },
  { word: 'Rabbit', forbidden: ['Bunny', 'Hop', 'Carrot', 'Ears', 'Burrow'] },
  { word: 'Mouse', forbidden: ['Cheese', 'Small', 'Squeak', 'Rodent', 'Cat'] },
  { word: 'Spider', forbidden: ['Web', 'Eight', 'Legs', 'Insect', 'Scary'] },
  { word: 'Bee', forbidden: ['Honey', 'Sting', 'Buzz', 'Hive', 'Flower'] },
  { word: 'Ant', forbidden: ['Small', 'Colony', 'Insect', 'Picnic', 'Queen'] },
  { word: 'Whale', forbidden: ['Big', 'Ocean', 'Blue', 'Mammal', 'Blowhole'] },
  { word: 'Jellyfish', forbidden: ['Sting', 'Sea', 'Tentacles', 'Clear', 'Float'] },
  { word: 'Sloth', forbidden: ['Slow', 'Tree', 'Hang', 'Lazy', 'Claws'] },

  // ── Places & travel ────────────────────────────────────────────────────────
  { word: 'Beach', forbidden: ['Sand', 'Sea', 'Sun', 'Waves', 'Holiday'] },
  { word: 'Library', forbidden: ['Books', 'Quiet', 'Read', 'Borrow', 'Shelves'] },
  { word: 'Airport', forbidden: ['Plane', 'Fly', 'Travel', 'Terminal', 'Luggage'] },
  { word: 'Museum', forbidden: ['Art', 'History', 'Exhibit', 'Gallery', 'Visit'] },
  { word: 'Lighthouse', forbidden: ['Light', 'Sea', 'Ships', 'Tower', 'Coast'] },
  { word: 'Volcano', forbidden: ['Lava', 'Erupt', 'Mountain', 'Ash', 'Magma'] },
  { word: 'Waterfall', forbidden: ['Water', 'Fall', 'River', 'Cliff', 'Niagara'] },
  { word: 'Igloo', forbidden: ['Ice', 'Snow', 'House', 'Eskimo', 'Cold'] },
  { word: 'Playground', forbidden: ['Swing', 'Slide', 'Kids', 'Park', 'Play'] },
  { word: 'Aquarium', forbidden: ['Fish', 'Tank', 'Water', 'Glass', 'Swim'] },
  { word: 'Passport', forbidden: ['Travel', 'Document', 'Country', 'Photo', 'Border'] },
  { word: 'Suitcase', forbidden: ['Pack', 'Travel', 'Luggage', 'Wheels', 'Clothes'] },
  { word: 'Traffic', forbidden: ['Cars', 'Jam', 'Road', 'Slow', 'Lights'] },
  { word: 'Escalator', forbidden: ['Stairs', 'Moving', 'Mall', 'Up', 'Step'] },
  { word: 'Submarine', forbidden: ['Underwater', 'Boat', 'Dive', 'Navy', 'Periscope'] },
  { word: 'Helicopter', forbidden: ['Fly', 'Blades', 'Rotor', 'Aircraft', 'Land'] },
  { word: 'Hotel', forbidden: ['Room', 'Stay', 'Bed', 'Book', 'Reception'] },
  { word: 'Restaurant', forbidden: ['Food', 'Menu', 'Waiter', 'Eat', 'Table'] },
  { word: 'Supermarket', forbidden: ['Shop', 'Food', 'Trolley', 'Aisle', 'Checkout'] },
  { word: 'Hospital', forbidden: ['Doctor', 'Sick', 'Nurse', 'Bed', 'Emergency'] },
  { word: 'Bank', forbidden: ['Money', 'Account', 'Cash', 'Loan', 'Savings'] },
  { word: 'Cinema', forbidden: ['Film', 'Screen', 'Popcorn', 'Ticket', 'Seats'] },
  { word: 'Theatre', forbidden: ['Play', 'Stage', 'Actors', 'Audience', 'Curtain'] },
  { word: 'Zoo', forbidden: ['Animals', 'Cage', 'Visit', 'Keeper', 'Enclosure'] },
  { word: 'Farm', forbidden: ['Animals', 'Field', 'Tractor', 'Crops', 'Barn'] },
  { word: 'Castle', forbidden: ['King', 'Stone', 'Moat', 'Tower', 'Medieval'] },
  { word: 'Bridge', forbidden: ['Cross', 'River', 'Span', 'Road', 'Over'] },
  { word: 'Tunnel', forbidden: ['Underground', 'Through', 'Dark', 'Dig', 'Train'] },
  { word: 'Desert', forbidden: ['Sand', 'Hot', 'Dry', 'Camel', 'Cactus'] },
  { word: 'Jungle', forbidden: ['Trees', 'Rainforest', 'Animals', 'Green', 'Vines'] },
  { word: 'Island', forbidden: ['Water', 'Surrounded', 'Beach', 'Sea', 'Land'] },
  { word: 'Mountain', forbidden: ['Climb', 'High', 'Peak', 'Everest', 'Hill'] },
  { word: 'Cave', forbidden: ['Dark', 'Rock', 'Underground', 'Bats', 'Explore'] },
  { word: 'Forest', forbidden: ['Trees', 'Woods', 'Green', 'Walk', 'Leaves'] },
  { word: 'River', forbidden: ['Water', 'Flow', 'Bank', 'Stream', 'Fish'] },
  { word: 'Lake', forbidden: ['Water', 'Still', 'Swim', 'Shore', 'Pond'] },
  { word: 'Skyscraper', forbidden: ['Tall', 'Building', 'City', 'Floors', 'High'] },
  { word: 'Stadium', forbidden: ['Sport', 'Crowd', 'Seats', 'Match', 'Pitch'] },
  { word: 'Market', forbidden: ['Stalls', 'Buy', 'Sell', 'Fruit', 'Trader'] },
  { word: 'Garage', forbidden: ['Car', 'Park', 'Door', 'Tools', 'House'] },
  { word: 'Basement', forbidden: ['Underground', 'House', 'Stairs', 'Cellar', 'Below'] },
  { word: 'Balcony', forbidden: ['Outside', 'Flat', 'Rail', 'View', 'Above'] },
  { word: 'Elevator', forbidden: ['Lift', 'Floors', 'Buttons', 'Up', 'Building'] },
  { word: 'Roundabout', forbidden: ['Cars', 'Circle', 'Road', 'Drive', 'Junction'] },
  { word: 'Motorway', forbidden: ['Road', 'Cars', 'Fast', 'Lanes', 'Drive'] },
  { word: 'Taxi', forbidden: ['Cab', 'Driver', 'Fare', 'Yellow', 'Ride'] },
  { word: 'Train', forbidden: ['Track', 'Station', 'Rail', 'Carriage', 'Platform'] },
  { word: 'Bus', forbidden: ['Wheels', 'Stop', 'Driver', 'Passengers', 'Route'] },
  { word: 'Ferry', forbidden: ['Boat', 'Water', 'Cars', 'Cross', 'Port'] },
  { word: 'Rocket', forbidden: ['Space', 'Launch', 'Fuel', 'Blast', 'NASA'] },
  { word: 'Hot air balloon', forbidden: ['Fly', 'Basket', 'Air', 'Float', 'Burner'] },
  { word: 'Tent', forbidden: ['Camping', 'Sleep', 'Poles', 'Outside', 'Zip'] },
  { word: 'Campfire', forbidden: ['Fire', 'Wood', 'Camp', 'Marshmallow', 'Burn'] },
  { word: 'Souvenir', forbidden: ['Holiday', 'Gift', 'Buy', 'Remember', 'Shop'] },
  { word: 'Sunburn', forbidden: ['Sun', 'Red', 'Skin', 'Burn', 'Cream'] },

  // ── Home & everyday objects ────────────────────────────────────────────────
  { word: 'Umbrella', forbidden: ['Rain', 'Wet', 'Open', 'Handle', 'Cover'] },
  { word: 'Keyboard', forbidden: ['Type', 'Keys', 'Computer', 'Letters', 'Piano'] },
  { word: 'Mirror', forbidden: ['Reflection', 'Glass', 'See', 'Look', 'Bathroom'] },
  { word: 'Toothbrush', forbidden: ['Teeth', 'Clean', 'Paste', 'Bathroom', 'Brush'] },
  { word: 'Scissors', forbidden: ['Cut', 'Paper', 'Sharp', 'Blades', 'Hair'] },
  { word: 'Camera', forbidden: ['Photo', 'Picture', 'Lens', 'Shoot', 'Flash'] },
  { word: 'Wallet', forbidden: ['Money', 'Cards', 'Pocket', 'Cash', 'Leather'] },
  { word: 'Blanket', forbidden: ['Warm', 'Bed', 'Cover', 'Sleep', 'Soft'] },
  { word: 'Compass', forbidden: ['North', 'Direction', 'Needle', 'Navigate', 'Map'] },
  { word: 'Calendar', forbidden: ['Dates', 'Months', 'Year', 'Days', 'Wall'] },
  { word: 'Chandelier', forbidden: ['Light', 'Ceiling', 'Crystal', 'Hang', 'Fancy'] },
  { word: 'Microwave', forbidden: ['Heat', 'Food', 'Kitchen', 'Oven', 'Beep'] },
  { word: 'Sunglasses', forbidden: ['Eyes', 'Sun', 'Shades', 'Wear', 'Dark'] },
  { word: 'Snorkel', forbidden: ['Swim', 'Breathe', 'Sea', 'Mask', 'Tube'] },
  { word: 'Origami', forbidden: ['Paper', 'Fold', 'Japanese', 'Crane', 'Art'] },
  { word: 'Trampoline', forbidden: ['Jump', 'Bounce', 'Garden', 'Springs', 'Kids'] },
  { word: 'Fridge', forbidden: ['Cold', 'Food', 'Kitchen', 'Freezer', 'Door'] },
  { word: 'Kettle', forbidden: ['Boil', 'Water', 'Tea', 'Hot', 'Whistle'] },
  { word: 'Toaster', forbidden: ['Bread', 'Toast', 'Pop', 'Slot', 'Kitchen'] },
  { word: 'Vacuum cleaner', forbidden: ['Clean', 'Carpet', 'Suck', 'Hoover', 'Dust'] },
  { word: 'Washing machine', forbidden: ['Clothes', 'Wash', 'Spin', 'Laundry', 'Drum'] },
  { word: 'Iron', forbidden: ['Clothes', 'Hot', 'Press', 'Creases', 'Board'] },
  { word: 'Hairdryer', forbidden: ['Hair', 'Hot', 'Blow', 'Wet', 'Dry'] },
  { word: 'Lamp', forbidden: ['Light', 'Bulb', 'Table', 'Switch', 'Shade'] },
  { word: 'Candle', forbidden: ['Wax', 'Flame', 'Light', 'Wick', 'Burn'] },
  { word: 'Clock', forbidden: ['Time', 'Hands', 'Tick', 'Wall', 'Hours'] },
  { word: 'Alarm', forbidden: ['Wake', 'Loud', 'Morning', 'Clock', 'Ring'] },
  { word: 'Pillow', forbidden: ['Sleep', 'Bed', 'Head', 'Soft', 'Case'] },
  { word: 'Curtains', forbidden: ['Window', 'Close', 'Fabric', 'Light', 'Hang'] },
  { word: 'Carpet', forbidden: ['Floor', 'Soft', 'Rug', 'Vacuum', 'Room'] },
  { word: 'Staircase', forbidden: ['Steps', 'Up', 'Climb', 'Down', 'Rail'] },
  { word: 'Doorbell', forbidden: ['Ring', 'Door', 'Visitor', 'Press', 'Chime'] },
  { word: 'Key', forbidden: ['Lock', 'Door', 'Open', 'Metal', 'Keyring'] },
  { word: 'Ladder', forbidden: ['Climb', 'Steps', 'Tall', 'Rungs', 'Reach'] },
  { word: 'Hammer', forbidden: ['Nail', 'Hit', 'Tool', 'Wood', 'Bang'] },
  { word: 'Screwdriver', forbidden: ['Screw', 'Turn', 'Tool', 'Flat', 'Cross'] },
  { word: 'Paintbrush', forbidden: ['Paint', 'Bristles', 'Wall', 'Art', 'Stroke'] },
  { word: 'Broom', forbidden: ['Sweep', 'Floor', 'Brush', 'Witch', 'Handle'] },
  { word: 'Bucket', forbidden: ['Water', 'Carry', 'Handle', 'Plastic', 'Fill'] },
  { word: 'Rope', forbidden: ['Tie', 'Knot', 'Long', 'Pull', 'Climb'] },
  { word: 'Battery', forbidden: ['Power', 'Charge', 'Remote', 'Energy', 'Dead'] },
  { word: 'Torch', forbidden: ['Light', 'Dark', 'Batteries', 'Shine', 'Flashlight'] },
  { word: 'Remote control', forbidden: ['TV', 'Buttons', 'Channel', 'Point', 'Lost'] },
  { word: 'Envelope', forbidden: ['Letter', 'Stamp', 'Post', 'Seal', 'Mail'] },
  { word: 'Stamp', forbidden: ['Post', 'Letter', 'Stick', 'Envelope', 'Mail'] },
  { word: 'Newspaper', forbidden: ['News', 'Read', 'Paper', 'Headlines', 'Daily'] },
  { word: 'Magazine', forbidden: ['Read', 'Pages', 'Glossy', 'Cover', 'Monthly'] },
  { word: 'Pencil', forbidden: ['Write', 'Lead', 'Rubber', 'Sharpen', 'Paper'] },
  { word: 'Notebook', forbidden: ['Write', 'Pages', 'Book', 'Notes', 'Paper'] },
  { word: 'Glue', forbidden: ['Stick', 'Paper', 'Craft', 'Bond', 'Tube'] },
  { word: 'Balloon', forbidden: ['Air', 'Blow', 'Pop', 'Party', 'Helium'] },
  { word: 'Ribbon', forbidden: ['Bow', 'Tie', 'Gift', 'Wrap', 'Fabric'] },
  { word: 'Mug', forbidden: ['Cup', 'Tea', 'Coffee', 'Handle', 'Drink'] },
  { word: 'Plate', forbidden: ['Food', 'Dish', 'Round', 'Eat', 'Table'] },
  { word: 'Fork', forbidden: ['Eat', 'Prongs', 'Cutlery', 'Knife', 'Food'] },
  { word: 'Basket', forbidden: ['Carry', 'Handle', 'Weave', 'Shopping', 'Picnic'] },

  // ── Tech, work & the office ────────────────────────────────────────────────
  { word: 'Netflix', forbidden: ['Streaming', 'Watch', 'Series', 'TV', 'Subscription'] },
  { word: 'Podcast', forbidden: ['Listen', 'Audio', 'Episode', 'Host', 'Show'] },
  { word: 'Password', forbidden: ['Login', 'Secret', 'Account', 'Forgot', 'Type'] },
  { word: 'Handshake', forbidden: ['Hands', 'Greet', 'Meet', 'Deal', 'Shake'] },
  { word: 'Laptop', forbidden: ['Computer', 'Screen', 'Portable', 'Keyboard', 'Work'] },
  { word: 'Smartphone', forbidden: ['Phone', 'Apps', 'Screen', 'Call', 'Mobile'] },
  { word: 'Charger', forbidden: ['Plug', 'Battery', 'Cable', 'Power', 'Phone'] },
  { word: 'Headphones', forbidden: ['Ears', 'Music', 'Listen', 'Wireless', 'Sound'] },
  { word: 'Printer', forbidden: ['Paper', 'Ink', 'Print', 'Office', 'Jam'] },
  { word: 'Wifi', forbidden: ['Internet', 'Signal', 'Wireless', 'Password', 'Connect'] },
  { word: 'Email', forbidden: ['Send', 'Inbox', 'Message', 'Reply', 'Computer'] },
  { word: 'Spreadsheet', forbidden: ['Excel', 'Cells', 'Rows', 'Data', 'Formula'] },
  { word: 'Meeting', forbidden: ['Room', 'Talk', 'Agenda', 'Calendar', 'Colleagues'] },
  { word: 'Deadline', forbidden: ['Date', 'Late', 'Finish', 'Pressure', 'Due'] },
  { word: 'Interview', forbidden: ['Job', 'Questions', 'Suit', 'Candidate', 'Hire'] },
  { word: 'Promotion', forbidden: ['Job', 'Raise', 'Higher', 'Boss', 'Work'] },
  { word: 'Boss', forbidden: ['Manager', 'Work', 'In charge', 'Employee', 'Office'] },
  { word: 'Colleague', forbidden: ['Work', 'Coworker', 'Office', 'Team', 'Job'] },
  { word: 'Salary', forbidden: ['Money', 'Pay', 'Job', 'Monthly', 'Wage'] },
  { word: 'Presentation', forbidden: ['Slides', 'Talk', 'Audience', 'PowerPoint', 'Present'] },
  { word: 'Whiteboard', forbidden: ['Marker', 'Write', 'Wipe', 'Board', 'Meeting'] },
  { word: 'Stapler', forbidden: ['Staples', 'Paper', 'Office', 'Click', 'Attach'] },
  { word: 'Photocopier', forbidden: ['Copy', 'Paper', 'Office', 'Machine', 'Scan'] },
  { word: 'Screenshot', forbidden: ['Screen', 'Capture', 'Image', 'Save', 'Phone'] },
  { word: 'Emoji', forbidden: ['Face', 'Text', 'Smiley', 'Symbol', 'Message'] },
  { word: 'Selfie', forbidden: ['Photo', 'Self', 'Phone', 'Camera', 'Front'] },
  { word: 'Hashtag', forbidden: ['Social media', 'Symbol', 'Tag', 'Twitter', 'Trend'] },
  { word: 'Video call', forbidden: ['Zoom', 'Screen', 'Mute', 'Camera', 'Meeting'] },
  { word: 'Notification', forbidden: ['Phone', 'Alert', 'Ping', 'Screen', 'App'] },
  { word: 'Robot', forbidden: ['Machine', 'Metal', 'Android', 'Program', 'Human'] },
  { word: 'Drone', forbidden: ['Fly', 'Camera', 'Remote', 'Propellers', 'Air'] },

  // ── Nature & weather ───────────────────────────────────────────────────────
  { word: 'Rainbow', forbidden: ['Colours', 'Rain', 'Sky', 'Arc', 'Pot of gold'] },
  { word: 'Winter', forbidden: ['Cold', 'Snow', 'Season', 'Ice', 'Christmas'] },
  { word: 'Snowman', forbidden: ['Snow', 'Carrot', 'Winter', 'Build', 'Frosty'] },
  { word: 'Tornado', forbidden: ['Wind', 'Storm', 'Spin', 'Twister', 'Destroy'] },
  { word: 'Thunderstorm', forbidden: ['Lightning', 'Rain', 'Loud', 'Clouds', 'Weather'] },
  { word: 'Cactus', forbidden: ['Desert', 'Spikes', 'Plant', 'Water', 'Green'] },
  { word: 'Sunflower', forbidden: ['Yellow', 'Sun', 'Tall', 'Seeds', 'Flower'] },
  { word: 'Fog', forbidden: ['Mist', 'Thick', 'See', 'Cloud', 'Morning'] },
  { word: 'Snowflake', forbidden: ['Snow', 'Ice', 'Unique', 'Fall', 'Winter'] },
  { word: 'Hurricane', forbidden: ['Storm', 'Wind', 'Tropical', 'Eye', 'Damage'] },
  { word: 'Earthquake', forbidden: ['Shake', 'Ground', 'Tremor', 'Richter', 'Damage'] },
  { word: 'Sunrise', forbidden: ['Sun', 'Morning', 'East', 'Up', 'Dawn'] },
  { word: 'Sunset', forbidden: ['Sun', 'Evening', 'West', 'Down', 'Dusk'] },
  { word: 'Moon', forbidden: ['Night', 'Sky', 'Full', 'Space', 'Astronaut'] },
  { word: 'Cloud', forbidden: ['Sky', 'White', 'Rain', 'Fluffy', 'Float'] },
  { word: 'Leaf', forbidden: ['Tree', 'Green', 'Autumn', 'Fall', 'Branch'] },
  { word: 'Acorn', forbidden: ['Oak', 'Tree', 'Squirrel', 'Nut', 'Seed'] },
  { word: 'Seashell', forbidden: ['Beach', 'Sea', 'Shell', 'Collect', 'Sand'] },
  { word: 'Coral reef', forbidden: ['Sea', 'Fish', 'Colourful', 'Underwater', 'Barrier'] },
  { word: 'Glacier', forbidden: ['Ice', 'Melt', 'Slow', 'Cold', 'Mountain'] },
  { word: 'Puddle', forbidden: ['Water', 'Rain', 'Splash', 'Ground', 'Jump'] },
  { word: 'Mud', forbidden: ['Dirt', 'Wet', 'Brown', 'Boots', 'Messy'] },

  // ── Sport & hobbies ────────────────────────────────────────────────────────
  { word: 'Football', forbidden: ['Ball', 'Goal', 'Sport', 'Kick', 'Team'] },
  { word: 'Marathon', forbidden: ['Run', 'Race', 'Miles', 'Finish', 'Training'] },
  { word: 'Bicycle', forbidden: ['Wheels', 'Pedal', 'Ride', 'Bike', 'Chain'] },
  { word: 'Rollercoaster', forbidden: ['Ride', 'Theme park', 'Loop', 'Scream', 'Track'] },
  { word: 'Basketball', forbidden: ['Hoop', 'Ball', 'Court', 'Dunk', 'NBA'] },
  { word: 'Tennis', forbidden: ['Racket', 'Ball', 'Court', 'Net', 'Serve'] },
  { word: 'Swimming', forbidden: ['Water', 'Pool', 'Stroke', 'Dive', 'Float'] },
  { word: 'Skiing', forbidden: ['Snow', 'Slope', 'Mountain', 'Poles', 'Winter'] },
  { word: 'Skateboard', forbidden: ['Wheels', 'Ride', 'Trick', 'Board', 'Ramp'] },
  { word: 'Surfing', forbidden: ['Wave', 'Board', 'Sea', 'Ride', 'Beach'] },
  { word: 'Yoga', forbidden: ['Stretch', 'Mat', 'Pose', 'Relax', 'Breathe'] },
  { word: 'Boxing', forbidden: ['Gloves', 'Punch', 'Ring', 'Fight', 'Round'] },
  { word: 'Golf', forbidden: ['Club', 'Ball', 'Hole', 'Course', 'Tee'] },
  { word: 'Chess', forbidden: ['Board', 'King', 'Pieces', 'Checkmate', 'Queen'] },
  { word: 'Jigsaw puzzle', forbidden: ['Pieces', 'Fit', 'Solve', 'Picture', 'Table'] },
  { word: 'Bowling', forbidden: ['Pins', 'Ball', 'Strike', 'Lane', 'Alley'] },
  { word: 'Darts', forbidden: ['Board', 'Throw', 'Bullseye', 'Pub', 'Points'] },
  { word: 'Hiking', forbidden: ['Walk', 'Boots', 'Trail', 'Mountain', 'Backpack'] },
  { word: 'Fishing', forbidden: ['Rod', 'Fish', 'Bait', 'Water', 'Catch'] },
  { word: 'Gardening', forbidden: ['Plants', 'Soil', 'Grow', 'Weeds', 'Garden'] },
  { word: 'Knitting', forbidden: ['Wool', 'Needles', 'Scarf', 'Stitch', 'Yarn'] },
  { word: 'Dancing', forbidden: ['Music', 'Move', 'Floor', 'Steps', 'Rhythm'] },
  { word: 'Juggling', forbidden: ['Balls', 'Throw', 'Catch', 'Circus', 'Hands'] },
  { word: 'Camping', forbidden: ['Tent', 'Outside', 'Sleep', 'Fire', 'Nature'] },

  // ── Entertainment & characters ─────────────────────────────────────────────
  { word: 'Guitar', forbidden: ['Strings', 'Music', 'Play', 'Instrument', 'Band'] },
  { word: 'Karaoke', forbidden: ['Sing', 'Microphone', 'Song', 'Lyrics', 'Bar'] },
  { word: 'Vampire', forbidden: ['Blood', 'Dracula', 'Fangs', 'Night', 'Bat'] },
  { word: 'Detective', forbidden: ['Crime', 'Clues', 'Solve', 'Police', 'Sherlock'] },
  { word: 'Treasure', forbidden: ['Gold', 'Pirate', 'Chest', 'Map', 'Buried'] },
  { word: 'Fireworks', forbidden: ['Explode', 'Sky', 'New Year', 'Bang', 'Colours'] },
  { word: 'Concert', forbidden: ['Music', 'Band', 'Live', 'Crowd', 'Tickets'] },
  { word: 'Orchestra', forbidden: ['Music', 'Conductor', 'Instruments', 'Classical', 'Violin'] },
  { word: 'Violin', forbidden: ['Strings', 'Bow', 'Music', 'Instrument', 'Play'] },
  { word: 'Piano', forbidden: ['Keys', 'Music', 'Play', 'Black and white', 'Instrument'] },
  { word: 'Drums', forbidden: ['Beat', 'Sticks', 'Music', 'Kit', 'Band'] },
  { word: 'Microphone', forbidden: ['Sing', 'Sound', 'Stage', 'Voice', 'Amplify'] },
  { word: 'Superhero', forbidden: ['Cape', 'Powers', 'Save', 'Comic', 'Villain'] },
  { word: 'Wizard', forbidden: ['Magic', 'Wand', 'Spell', 'Hat', 'Harry Potter'] },
  { word: 'Dragon', forbidden: ['Fire', 'Scales', 'Wings', 'Myth', 'Knight'] },
  { word: 'Ghost', forbidden: ['Scary', 'White', 'Haunt', 'Spirit', 'Boo'] },
  { word: 'Zombie', forbidden: ['Undead', 'Brains', 'Walk', 'Horror', 'Slow'] },
  { word: 'Pirate', forbidden: ['Ship', 'Treasure', 'Parrot', 'Eye patch', 'Sea'] },
  { word: 'Knight', forbidden: ['Armour', 'Sword', 'Castle', 'Horse', 'Medieval'] },
  { word: 'Clown', forbidden: ['Circus', 'Funny', 'Nose', 'Makeup', 'Scary'] },
  { word: 'Magician', forbidden: ['Magic', 'Trick', 'Hat', 'Rabbit', 'Wand'] },
  { word: 'Circus', forbidden: ['Tent', 'Clown', 'Acrobat', 'Ring', 'Animals'] },
  { word: 'Cartoon', forbidden: ['Animation', 'Draw', 'Kids', 'TV', 'Characters'] },
  { word: 'Sequel', forbidden: ['Film', 'Second', 'Follow', 'Part two', 'Movie'] },
  { word: 'Trailer', forbidden: ['Film', 'Preview', 'Cinema', 'Clip', 'Coming soon'] },
  { word: 'Spoiler', forbidden: ['Ending', 'Ruin', 'Reveal', 'Film', 'Warning'] },

  // ── Clothing ───────────────────────────────────────────────────────────────
  { word: 'Scarf', forbidden: ['Neck', 'Wool', 'Winter', 'Wrap', 'Warm'] },
  { word: 'Gloves', forbidden: ['Hands', 'Fingers', 'Winter', 'Warm', 'Pair'] },
  { word: 'Hat', forbidden: ['Head', 'Wear', 'Cap', 'Top', 'Brim'] },
  { word: 'Socks', forbidden: ['Feet', 'Pair', 'Shoes', 'Wear', 'Odd'] },
  { word: 'Boots', forbidden: ['Feet', 'Shoes', 'Laces', 'Walk', 'Leather'] },
  { word: 'Jeans', forbidden: ['Denim', 'Blue', 'Trousers', 'Pockets', 'Wear'] },
  { word: 'Tie', forbidden: ['Neck', 'Shirt', 'Knot', 'Suit', 'Formal'] },
  { word: 'Raincoat', forbidden: ['Rain', 'Wet', 'Waterproof', 'Coat', 'Hood'] },
  { word: 'Swimsuit', forbidden: ['Swim', 'Pool', 'Beach', 'Wear', 'Water'] },
  { word: 'Pyjamas', forbidden: ['Sleep', 'Bed', 'Night', 'Wear', 'Comfy'] },
  { word: 'Apron', forbidden: ['Cook', 'Kitchen', 'Tie', 'Protect', 'Chef'] },
  { word: 'Backpack', forbidden: ['Bag', 'Shoulders', 'Carry', 'School', 'Straps'] },

  // ── Jobs & people ──────────────────────────────────────────────────────────
  { word: 'Doctor', forbidden: ['Hospital', 'Patient', 'Medicine', 'Sick', 'Nurse'] },
  { word: 'Teacher', forbidden: ['School', 'Class', 'Students', 'Learn', 'Lesson'] },
  { word: 'Dentist', forbidden: ['Teeth', 'Drill', 'Mouth', 'Cavity', 'Clean'] },
  { word: 'Firefighter', forbidden: ['Fire', 'Hose', 'Truck', 'Rescue', 'Helmet'] },
  { word: 'Astronaut', forbidden: ['Space', 'NASA', 'Moon', 'Rocket', 'Suit'] },
  { word: 'Nurse', forbidden: ['Hospital', 'Doctor', 'Patient', 'Care', 'Scrubs'] },
  { word: 'Ambulance', forbidden: ['Hospital', 'Emergency', 'Siren', 'Paramedic', 'Van'] },
  { word: 'Grandmother', forbidden: ['Grandma', 'Family', 'Old', 'Mother', 'Nan'] },
  { word: 'Chef', forbidden: ['Cook', 'Kitchen', 'Restaurant', 'Food', 'Hat'] },
  { word: 'Barista', forbidden: ['Coffee', 'Cafe', 'Make', 'Milk', 'Order'] },
  { word: 'Pilot', forbidden: ['Plane', 'Fly', 'Cockpit', 'Captain', 'Air'] },
  { word: 'Farmer', forbidden: ['Farm', 'Crops', 'Animals', 'Tractor', 'Field'] },
  { word: 'Plumber', forbidden: ['Pipes', 'Water', 'Leak', 'Fix', 'Toilet'] },
  { word: 'Electrician', forbidden: ['Wires', 'Power', 'Fix', 'Electricity', 'Sockets'] },
  { word: 'Hairdresser', forbidden: ['Hair', 'Cut', 'Salon', 'Scissors', 'Style'] },
  { word: 'Lawyer', forbidden: ['Court', 'Law', 'Case', 'Judge', 'Client'] },
  { word: 'Accountant', forbidden: ['Numbers', 'Money', 'Tax', 'Books', 'Figures'] },
  { word: 'Journalist', forbidden: ['News', 'Write', 'Story', 'Reporter', 'Paper'] },
  { word: 'Photographer', forbidden: ['Camera', 'Photo', 'Shoot', 'Pictures', 'Lens'] },
  { word: 'Vet', forbidden: ['Animals', 'Doctor', 'Pets', 'Treat', 'Clinic'] },
  { word: 'Librarian', forbidden: ['Books', 'Library', 'Quiet', 'Shelves', 'Borrow'] },
  { word: 'Delivery driver', forbidden: ['Parcel', 'Van', 'Deliver', 'Door', 'Package'] },

  // ── Ideas & moments ────────────────────────────────────────────────────────
  { word: 'Birthday', forbidden: ['Cake', 'Candles', 'Party', 'Presents', 'Age'] },
  { word: 'Wedding', forbidden: ['Marriage', 'Bride', 'Groom', 'Ring', 'Church'] },
  { word: 'Secret', forbidden: ['Tell', 'Hide', 'Keep', 'Whisper', 'Confidential'] },
  { word: 'Surprise', forbidden: ['Unexpected', 'Shock', 'Party', 'Gift', 'Wow'] },
  { word: 'Nightmare', forbidden: ['Dream', 'Bad', 'Sleep', 'Scary', 'Wake'] },
  { word: 'Deja vu', forbidden: ['Before', 'Again', 'Feeling', 'Memory', 'French'] },
  { word: 'Nostalgia', forbidden: ['Past', 'Memories', 'Miss', 'Old', 'Feeling'] },
  { word: 'Gossip', forbidden: ['Talk', 'Rumour', 'Whisper', 'People', 'Secret'] },
  { word: 'Queue', forbidden: ['Line', 'Wait', 'Stand', 'People', 'Order'] },
  { word: 'Silence', forbidden: ['Quiet', 'Noise', 'Nothing', 'Hush', 'Sound'] },
  { word: 'Echo', forbidden: ['Sound', 'Repeat', 'Cave', 'Shout', 'Back'] },
  { word: 'Shadow', forbidden: ['Dark', 'Light', 'Follow', 'Shape', 'Sun'] },
  { word: 'Reflection', forbidden: ['Mirror', 'Water', 'See', 'Image', 'Bounce'] },
  { word: 'Gravity', forbidden: ['Fall', 'Down', 'Newton', 'Earth', 'Pull'] },
  { word: 'Recycling', forbidden: ['Bin', 'Plastic', 'Waste', 'Green', 'Reuse'] },
  { word: 'Charity', forbidden: ['Give', 'Money', 'Help', 'Donate', 'Cause'] },
  { word: 'Anniversary', forbidden: ['Year', 'Celebrate', 'Date', 'Marriage', 'Remember'] },
  { word: 'Retirement', forbidden: ['Work', 'Stop', 'Pension', 'Old', 'Age'] },
  { word: 'Homework', forbidden: ['School', 'Study', 'Teacher', 'Assignment', 'Home'] },
  { word: 'Graduation', forbidden: ['University', 'Cap', 'Gown', 'Degree', 'Ceremony'] },
  { word: 'Reunion', forbidden: ['Meet', 'Again', 'Family', 'School', 'Gather'] },
];

export function shuffledDeck() {
  const a = [...CARDS];
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
}
