export const questions = [
  "What is the best thing about being a kid?",
  "What would you do if you won the lottery tomorrow?",
  "What is the most overrated thing in the world?",
  "What is the worst movie of all time?",
  "What is the best thing to do on a rainy day?",
  "What would you put in a time capsule?",
  "What is the weirdest food combination that actually tastes good?",
  "What is the most useless superpower?",
  "What is the best thing about being old?",
  "What would be the worst superpower to have?",
  "What is the most underrated movie ever made?",
  "What is the best thing to do when you're bored?",
  "What is the most annoying thing a person can do?",
  "What would you do if you were invisible for a day?",
  "What is the worst thing to find in your bed?",
  "What is the best way to spend a Sunday?",
  "What is the most bizarre trend of the last decade?",
  "What is the best excuse to get out of something you don't want to do?",
  "What animal would make the best president?",
  "What is the worst thing to step on barefoot?",
  "What is the funniest thing that has ever happened to you?",
  "What is the best thing to eat when you're sick?",
  "What is the strangest thing people find attractive?",
  "What is the most pointless thing humans do?",
  "What would be the worst job in the world?",
  "What is the best thing about living alone?",
  "What is the weirdest dream you've ever had?",
  "What is the best thing about working from home?",
  "What is the most dangerous thing most people consider totally safe?",
  "What would a dog say if it could talk for one minute?",
  "What is the worst thing about being famous?",
  "What is the best thing to binge-watch on a sick day?",
  "What is something everyone should try at least once?",
  "What is the most useful skill a person can have?",
  "What is the most annoying habit a roommate can have?",
  "What is the worst gift you could give someone?",
  "What would you do if you were stranded on a desert island?",
  "What is the best fast food item ever created?",
  "What is the most ridiculous law that should exist?",
  "What is the strangest thing you've ever eaten?",
  "What would you change about the internet?",
  "What is the best thing about summer?",
  "What is the worst holiday tradition?",
  "What is the most overused phrase in the English language?",
  "What is something that was better before the internet?",
  "What is the best thing about having a pet?",
  "What would be the first thing you'd do if you became president?",
  "What is the most satisfying sound in the world?",
  "What is the best thing to say to get out of a parking ticket?",
  "What is the worst smell in the world?",
  "What would you want your last meal to be?",
  "What is the best invention of the last 50 years?",
  "What is the most overpriced thing people still buy?",
  "What is the best way to annoy someone without them knowing it's you?",
  "What would the world be like if cats were in charge?",
  "What is the most embarrassing thing to be caught doing?",
  "What is the best thing about being an adult?",
  "What is the weirdest phobia someone could have?",
  "What is the worst date idea?",
  "What is the best thing about your hometown?",
  "What is the most illegal thing that should be legal?",
  "What is something people pretend to like but actually hate?",
  "What would be the hardest thing to give up for a month?",
  "What is the best thing about getting older?",
  "What is the strangest tradition your family has?",
  "What is the worst thing about social media?",
  "What is the best smell in the world?",
  "What would aliens think is the weirdest thing about humans?",
  "What is the most underrated pizza topping?",
  "What is the best thing about having siblings?",
  "What is the most overrated tourist destination?",
  "What would you do with a completely free day?",
  "What is the worst thing about flying?",
  "What is the best thing about winter?",
  "What is the most useful app on your phone?",
  "What is the worst thing about being in a relationship?",
  "What is the best thing about being single?",
  "What is something that always makes you feel better?",
  "What would be the worst thing to say on a first date?",
  "What is the most useless thing you own but can't throw away?",
  "What is the best way to spend $100?",
  "What is the most annoying sound in the world?",
  "What would you put on a billboard for everyone to see?",
  "What is the worst movie sequel ever made?",
  "What is the best thing about living in a city?",
  "What is something you're surprisingly good at?",
  "What is the worst thing you could find in your food?",
  "What would be the funniest thing to say at a wedding?",
  "What is the most delicious thing a grandparent makes?",
  "What is the worst thing about mornings?",
  "What is the best thing about Fridays?",
  "What would you do if you found $1000 on the street?",
  "What is the most ridiculous thing people argue about?",
  "What is the best thing you've ever eaten?",
  "What is the worst advice ever given?",
  "What is something that looked easy but turned out to be very hard?",
  "What would be the worst song to get stuck in your head?",
  "What is the most bizarre thing that's ever happened to you?",
  "What is the best thing about working in an office?",
  "What is the worst thing about working in an office?",
  "What would the perfect day look like?",
];

export function getRandomQuestions(count = 5, exclude = [], custom = null) {
  const bank = Array.isArray(custom) && custom.length ? custom : questions;
  const pool = bank.filter(q => !exclude.includes(q));
  const shuffled = (pool.length ? pool : bank).slice().sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
