export const PREDEFINED_QUESTIONS = [
    "What's the first thing most people do when they wake up?",
    "What's the most annoying sound in the world?",
    "What's the best pizza topping?",
    "Which superpower would most people choose?",
    "What's the worst movie genre?",
    "Where do most people want to go on vacation?",
    "What's the most overrated food?",
    "What's the best way to spend a Sunday?",
    "What's the most addictive social media platform?",
    "What's the worst household chore?",
    "What's the best season of the year?",
    "What's the most useful invention of all time?",
    "What's the most common pet name?",
    "What's the best fast food restaurant?",
    "What's the most boring sport to watch?",
    "What's the worst fashion trend ever?",
    "What's the best breakfast food?",
    "What's the most common excuse for being late?",
    "What's the most relaxing hobby?",
    "What's the best ice cream flavor?",
    "What's the worst topping to put on a burger?",
    "What's the best movie snack?",
    "What's the most useless school subject?",
    "What's the best board game?",
    "What's the worst thing about Monday mornings?",
    "What's the best sandwich filling?",
    "What's the most annoying TV commercial?",
    "What's the best chocolate bar?",
    "What's the worst pain to experience?",
    "What's the best theme park ride?",
    "What's the most common phobia?",
    "What's the best video game genre?",
    "What's the worst smell?",
    "What's the best food to eat when sick?",
    "What's the most annoying personality trait?",
    "What's the best way to cool off on a hot day?",
    "What's the worst present to receive?",
    "What's the best cartoon character?",
    "What's the most difficult part of adulting?",
    "What's the best fruit?",
    "What's the worst vegetable?",
    "What's the best movie genre?",
    "What's the most important meal of the day?",
    "What's the best pizza chain?",
    "What's the worst airport experience?",
    "What's the best way to spend $100?",
    "What's the most annoying habit?",
    "What's the best holiday?",
    "What's the worst thing about winter?",
    "What's the best comfort food?",
    "What's the most overrated celebrity?",
    "What's the best phone app?",
    "What's the worst trend on social media?",
    "What's the best Disney movie?",
    "What's the most annoying question to be asked?",
    "What's the best midnight snack?",
    "What's the worst song to get stuck in your head?",
    "What's the best way to exercise?",
    "What's the most important invention in the last 100 years?",
    "What's the best childhood memory?",
    "What's the worst cooking mistake?",
    "What's the best way to relax after work?",
    "What's the most annoying office behavior?",
    "What's the best movie sequel ever made?",
    "What's the worst car color?",
    "What's the best restaurant type?",
    "What's the most annoying social media feature?",
    "What's the best way to start the day?",
    "What's the worst fashion accessory?",
    "What's the best room in a house?",
    "What's the most useful kitchen appliance?",
    "What's the worst video game genre?",
    "What's the best way to spend a rainy day?",
    "What's the most annoying thing about technology?",
    "What's the best childhood game?",
    "What's the worst pizza topping?",
    "What's the best streaming service?",
    "What's the most annoying thing about public transport?",
    "What's the best book genre?",
    "What's the worst food combination?",
    "What's the best way to celebrate a birthday?",
    "What's the most annoying thing about social gatherings?",
    "What's the best pet for an apartment?",
    "What's the worst music genre?",
    "What's the best way to make friends?",
    "What's the most annoying thing about shopping?",
    "What's the best dessert?",
    "What's the worst household task?",
    "What's the best weekend activity?",
    "What's the most annoying thing about smartphones?",
    "What's the best way to stay healthy?",
    "What's the worst weather condition?",
    "What's the best childhood toy?",
    "What's the most annoying thing about dating?",
    "What's the best way to save money?",
    "What's the worst common food?",
    "What's the best career path?",
    "What's the most annoying thing about social media?",
    "What's the best way to travel?",
    "What's the worst habit to have?",
    "What's the best time of day?",
    "What's the most annoying thing about weddings?",
    "What's the best hobby to have?",
    "What's the worst thing about growing up?",
    "What's the best way to spend a vacation?",
    "What's the most annoying thing about neighbors?",
    "What's the best fast food side dish?",

    /*
      Appended 20 Aug 2026, taking the bank from 107 to 211.

      APPEND ONLY. questionId is the INDEX into this array, and every submission
      and tally ever recorded stores that index. Inserting or reordering would
      silently re-point months of history at different questions, and nothing
      would fail loudly when it happened.

      Why: at 107 questions and five a day the deck ran out after 21 days, so a
      daily player started seeing repeats in week three. At 211 that becomes 42
      days. games/daily/dailyQuestions.js already guarantees no repeat inside a
      cycle, so bank size is now the only thing setting how long a returning
      player goes without seeing the same question twice.

      Style follows the existing set on purpose: short, one likely crowd answer,
      answerable in a word or two. Herd Mentality is about matching the majority,
      so a question with fifty equally valid answers is a bad question here — it
      splits the vote and nobody matches anybody.
    */
    "What's the best flavour of ice cream?",
    "What's the best thing to put on toast?",
    "What's the most common takeaway order?",
    "What's the best biscuit to dunk in tea?",
    "What's the worst thing to find in your sandwich?",
    "What's the most popular fizzy drink?",
    "What's the worst thing about eating out?",
    "What fruit goes off the fastest?",
    "What's the best snack for a road trip?",
    "What's the most divisive food?",
    "What's the best pasta shape?",
    "What's the worst flavour of crisps?",
    "What's the most common pet?",
    "What animal would be the worst to meet in the dark?",
    "What's the smartest animal?",
    "What's the most annoying insect?",
    "What animal makes the best mascot?",
    "What's the scariest animal at the zoo?",
    "What bird do most people see every day?",
    "What animal would be the hardest to keep as a pet?",
    "What do people lose most often?",
    "What's the most useless kitchen gadget?",
    "What's the first thing you'd grab in a fire?",
    "What's always at the bottom of a bag?",
    "What's the most annoying thing to assemble?",
    "What room gets messiest first?",
    "What's the most common thing to forget when packing?",
    "What's the worst chore?",
    "What breaks the soonest after you buy it?",
    "What's the most common colour of a front door?",
    "What's the best season?",
    "What's the first sign of summer?",
    "What's the best thing about rain?",
    "What's the most British thing to complain about?",
    "What's the worst part of flying?",
    "What do people always forget at a hotel?",
    "What's the worst seat on a plane?",
    "What's the most common holiday souvenir?",
    "What's the most stressful part of a journey?",
    "What's the worst thing about Mondays?",
    "What's the best school subject?",
    "What's the worst school subject?",
    "What's the most annoying thing in an office?",
    "What's the best perk a job can have?",
    "What's the most overused word in a meeting?",
    "What's the first thing people do at their desk?",
    "What app do people open first in the morning?",
    "What's the most annoying notification?",
    "What's the worst password people still use?",
    "What device do people break most often?",
    "What's the most common reason a phone dies?",
    "What's the most annoying thing about Wi-Fi?",
    "What's the first thing people Google?",
    "What's the best film to watch at Christmas?",
    "What's the worst thing about the cinema?",
    "What instrument do most people try to learn?",
    "What's the most famous painting?",
    "What's the best card game?",
    "What song does everyone know the words to?",
    "What's the best type of music to clean the house to?",
    "What's the most popular sport in the world?",
    "What's the worst weather to play sport in?",
    "What's the best playground equipment?",
    "What sport is hardest to watch on TV?",
    "What's the most common name?",
    "What's the worst thing to say at a wedding?",
    "What's the most awkward small talk topic?",
    "What's the best way to end a phone call?",
    "What's the most common lie people tell?",
    "What's the worst house guest habit?",
    "What's the best excuse to leave a party early?",
    "What's the most annoying driving habit?",
    "What's the first thing people notice about someone?",
    "What's the worst place to get an itch?",
    "What's the most common New Year's resolution?",
    "What's the hardest habit to break?",
    "What wakes people up in the night most?",
    "What's the most calming colour?",
    "What's the best smell?",
    "What colour is most people's car?",
    "What sound is the most satisfying?",
    "What do people waste money on most?",
    "What's the worst thing about supermarkets?",
    "What's the most common impulse buy?",
    "What's always more expensive than it should be?",
    "What's the worst time to get a phone call?",
    "What day of the week is the worst?",
    "What takes people the longest in the morning?",
    "What's the worst thing to run out of?",
    "What's the best thing to put in a lunchbox?",
    "What's the first thing people buy in a new house?",
    "What's the worst thing about camping?",
    "What's the best way to cook an egg?",
    "What's the most common thing to argue about?",
    "What's the worst thing to lose on holiday?",
    "What's the best thing to do on a rainy day?",
    "What's the most annoying queue to be stuck in?",
    "What's the best time of year to be born?",
    "What's the most useless superpower?",
    "What's the worst way to be woken up?",
    "What's the most overrated holiday?",
    "What's the best thing about being an adult?",
    "What would most people do with a free hour?",
    "What's the most common thing in a junk drawer?"
  ];