export const PREDEFINED_QUESTIONS = [
    "What's the first thing most people do when they wake up?",
    "What's the most annoying sound in the world?",
    "What's the best pizza topping?",
    "Which superpower would most people choose?",
    "What's the worst movie genre?",
    "Where do most people want to go on vacation?",
    "What's the most overrated food?",
    "What's the best way to spend a Sunday?",
    "What's the most addictive social media platform?",
    "What's the worst household chore?",
    "What's the best season of the year?",
    "What's the most useful invention of all time?",
    "What's the most common pet name?",
    "What's the best fast food restaurant?",
    "What's the most boring sport to watch?",
    "What's the worst fashion trend ever?",
    "What's the best breakfast food?",
    "What's the most common excuse for being late?",
    "What's the most relaxing hobby?",
    "What's the best ice cream flavor?",
    "What's the worst topping to put on a burger?",
    "What's the best movie snack?",
    "What's the most useless school subject?",
    "What's the best board game?",
    "What's the worst thing about Monday mornings?",
    "What's the best sandwich filling?",
    "What's the most annoying TV commercial?",
    "What's the best chocolate bar?",
    "What's the worst pain to experience?",
    "What's the best theme park ride?",
    "What's the most common phobia?",
    "What's the best video game genre?",
    "What's the worst smell?",
    "What's the best food to eat when sick?",
    "What's the most annoying personality trait?",
    "What's the best way to cool off on a hot day?",
    "What's the worst present to receive?",
    "What's the best cartoon character?",
    "What's the most difficult part of adulting?",
    "What's the best fruit?",
    "What's the worst vegetable?",
    "What's the best movie genre?",
    "What's the most important meal of the day?",
    "What's the best pizza chain?",
    "What's the worst airport experience?",
    "What's the best way to spend $100?",
    "What's the most annoying habit?",
    "What's the best holiday?",
    "What's the worst thing about winter?",
    "What's the best comfort food?",
    "What's the most overrated celebrity?",
    "What's the best phone app?",
    "What's the worst trend on social media?",
    "What's the best Disney movie?",
    "What's the most annoying question to be asked?",
    "What's the best midnight snack?",
    "What's the worst song to get stuck in your head?",
    "What's the best way to exercise?",
    "What's the most important invention in the last 100 years?",
    "What's the best childhood memory?",
    "What's the worst cooking mistake?",
    "What's the best way to relax after work?",
    "What's the most annoying office behavior?",
    "What's the best movie sequel ever made?",
    "What's the worst car color?",
    "What's the best restaurant type?",
    "What's the most annoying social media feature?",
    "What's the best way to start the day?",
    "What's the worst fashion accessory?",
    "What's the best room in a house?",
    "What's the most useful kitchen appliance?",
    "What's the worst video game genre?",
    "What's the best way to spend a rainy day?",
    "What's the most annoying thing about technology?",
    "What's the best childhood game?",
    "What's the worst pizza topping?",
    "What's the best streaming service?",
    "What's the most annoying thing about public transport?",
    "What's the best book genre?",
    "What's the worst food combination?",
    "What's the best way to celebrate a birthday?",
    "What's the most annoying thing about social gatherings?",
    "What's the best pet for an apartment?",
    "What's the worst music genre?",
    "What's the best way to make friends?",
    "What's the most annoying thing about shopping?",
    "What's the best dessert?",
    "What's the worst household task?",
    "What's the best weekend activity?",
    "What's the most annoying thing about smartphones?",
    "What's the best way to stay healthy?",
    "What's the worst weather condition?",
    "What's the best childhood toy?",
    "What's the most annoying thing about dating?",
    "What's the best way to save money?",
    "What's the worst common food?",
    "What's the best career path?",
    "What's the most annoying thing about social media?",
    "What's the best way to travel?",
    "What's the worst habit to have?",
    "What's the best time of day?",
    "What's the most annoying thing about weddings?",
    "What's the best hobby to have?",
    "What's the worst thing about growing up?",
    "What's the best way to spend a vacation?",
    "What's the most annoying thing about neighbors?",
    "What's the best fast food side dish?"
  ];