#!/usr/bin/env node
/**
 * Copy the hue grid to the browser.
 *
 *   node scripts/sync-huegrid.js        (or: npm run sync:huegrid)
 *
 * The browser needs the rule so a long word turns red BEFORE it is sent, and
 * huematch-logic-check.js compares the two files byte for byte because silent
 * drift means the warning light says green while the server charges a point —
 * which reads to the player as the game cheating.
 *
 * That check was written with "re-copy it across keeping the frontend header"
 * as the fix, i.e. a manual step. A manual step in the middle of a guard is a
 * guard people learn to route around, so here it is as one command.
 *
 * The server copy is the source of truth. This only ever writes the browser one.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const SERVER = path.join(here, '..', 'src', 'games', 'huematch', 'grid.js');
const BROWSER = path.join(here, '..', '..', 'frontend', 'src', 'lib', 'hueGrid.js');

const HEADER = `/*
  A VERBATIM COPY of backend/src/games/huematch/grid.js.

  The browser needs it to paint the board and to show the scoring rings at the
  reveal. The server keeps the authoritative copy — this one only draws.

  DO NOT EDIT THIS FILE. Edit the server copy and run:

      cd backend && npm run sync:huegrid

  Two copies of one rule drift, and this pair would drift SILENTLY: the board
  would paint one colour for square G4 while the server scored a different one,
  and the only symptom would be players insisting the colours are wrong.
  backend/scripts/huematch-logic-check.js compares the two byte for byte below
  this header and fails if they differ.
*/

`;

/*
  A missing browser copy is the case this command most needs to handle, not the
  one it refuses. It used to print "nothing to sync" and exit 1 — so on a fresh
  checkout where the file had never been generated, or after someone deleted it,
  the one documented way to produce it declined to. Meanwhile the drift check
  skips silently when the file is absent, so a missing copy was neither detected
  nor fixable by the command that names itself as the fix.

  It refuses only when the FRONTEND is not in this checkout at all, which is a
  real backend-only deploy rather than a file waiting to be written.
*/
if (!fs.existsSync(path.dirname(BROWSER))) {
  console.error(`No frontend in this checkout (${path.dirname(BROWSER)}) — nothing to sync.`);
  process.exit(1);
}
const creating = !fs.existsSync(BROWSER);

const server = fs.readFileSync(SERVER, 'utf8');
const before = creating ? null : fs.readFileSync(BROWSER, 'utf8');
const after = HEADER + server;

if (before === after) {
  console.log('hue grid — the browser copy already matches the server copy');
  process.exit(0);
}

fs.writeFileSync(BROWSER, after);
console.log(creating
  ? 'hue grid — browser copy created from the server copy'
  : 'hue grid — browser copy updated from the server copy');
console.log(`  ${BROWSER}`);
